### ISSUE TITLE
Repeated keywords support

### ISSUE THREAD

**Issue by erseco** [linkedin/nginx-config-builder#10]
Hello, I'm trying to define some `add_header` directives but I can't because the system detects it like repeated keyword, is possible to solve this?

Best!

**Comment by lorencarvalho** [comment]
hi @erseco,

yep! there's a helper for this exact issue:

```
>>> from nginx.config.helpers import duplicate_options
>>> duplicate_options('add_header', ['header 1', 'header 2'])

add_header header 1;
add_header header 2;
```

This helper is just creating an `EmptyBock` object and adding each section via `EmptyBlock.sections.add`

lmk if that helps!

**Comment by erseco** [comment]
Works like a charm, thanks!
